name: Python Setup Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Verificar arquivos alterados
      id: files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          requirements.txt
          setup.py
          *.py

    - name: Exibir arquivos alterados
      run: echo "Arquivos alterados: ${{ steps.files.outputs.files }}"

    - name: Instalar dependências
      if: ${{ steps.files.outputs.files != '' }}  # Só instala as dependências se houver arquivos alterados
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Confirmar versão do Python e pip
      run: |
        python --version
        pip --version
